[package]
name = "automergeable-view"
version = "0.1.0"
edition = "2018"

[dependencies]
automerge = { git = "https://github.com/automerge/automerge-rs", branch = "experiment" }
smol_str = "0.1.21"

[dev-dependencies]
serde_json = "1.0.78"
